# -------------------
# Basic configuration
# -------------------
setopt HIST_IGNORE_ALL_DUPS
typeset -g HISTFILE=${ZDOTDIR:-${HOME}}/.zsh_history
bindkey -e
WORDCHARS=${WORDCHARS//[\/]}

zstyle ':zim:git' aliases-prefix 'g'
zstyle ':zim:termtitle' format '%1~'
zstyle ':zim:termtitle' hooks 'preexec' 'precmd'
zstyle ':zim:termtitle:preexec' format '${${(A)=1}[1]}'
zstyle ':zim:termtitle:precmd'  format '%1~'

# Initialize modules
ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  if (( ${+commands[curl]} )); then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  else
    mkdir -p ${ZIM_HOME} && wget -nv -O ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  fi
fi
# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

# Post-init module configuration
zmodload -F zsh/terminfo +p:terminfo
# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
for key ('^[[A' '^P' ${terminfo[kcuu1]}) bindkey ${key} history-substring-search-up
for key ('^[[B' '^N' ${terminfo[kcud1]}) bindkey ${key} history-substring-search-down
for key ('k') bindkey -M vicmd ${key} history-substring-search-up
for key ('j') bindkey -M vicmd ${key} history-substring-search-down
unset key

# ------------------
# User configuration
# ------------------

if (( $+commands[zoxide] )); then
  # export _ZO_ECHO=1
  eval "$(zoxide init zsh)"
  alias zz=__zoxide_zi
  # alias cd=z
fi


if (( $+commands[lazygit] )); then
  alias lg=lazygit
fi

if (( $+commands[lazydocker] )); then
  alias lzd=lazydocker
fi

if (( $+commands[cargo] )); then
  export PATH="~/.cargo/bin:${PATH}"
fi

if (( $+commands[go] )); then
  export PATH="~/go/bin:${PATH}"
fi

alias ls='ls --color=auto'
alias ll='ls -hl'
alias la='ll -a'

if (( $+commands[eza] )); then
  alias ls='eza --color=auto --group-directories-first'
  alias ll='ls -l --git'        # Long format, git status
  alias la='ll -a'              # Long format, all files
  alias lr='ll -T'              # Long format, recursive as a tree
  alias lx='ll -sextension'     # Long format, sort by extension
  alias lk='ll -ssize'          # Long format, largest file size last
  alias lt='ll -smodified'      # Long format, newest modification time last
  alias lc='ll -schanged'       # Long format, newest status change (ctime) last
fi

if (( $+commands[tmux] )); then
  alias t="tmux new -A -s 0"
  tt() {
    local session_name
    if [ "$PWD" = "$HOME" ]; then
        session_name="~"
    else
        session_name=$(basename "$PWD" | tr '.:' '__')
    fi
    tmux new-session -A -s "$session_name"
  }
fi

if (( $+commands[nvim] )); then
  alias nv="nvim"
fi

if (( $+commands[claude] )); then
  alias cl="claude --dangerously-skip-permissions"
fi

alias vz="vim ~/.zshrc && source ~/.zshrc"
alias vzz="vim ~/.zimrc"
alias vzu="zimfw install && zimfw update"

unalias gh
alias gfc="git clone --recursive"
alias gst="git status"

export EDITOR=vim
export PATH="$HOME/.local/bin:$PATH"

proxy () {
  # local PROXY="socks5://127.0.0.1:7890"
  local PROXY="http://127.0.0.1:7890"
  export ALL_PROXY="${PROXY}"
  export HTTP_PROXY="${PROXY}"
  export HTTPS_PROXY="${PROXY}"
  git config --global http.proxy ${PROXY}
  git config --global https.proxy ${PROXY}
}

unproxy () {
  unset ALL_PROXY
  unset HTTP_PROXY
  unset HTTPS_PROXY
  git config --global --unset http.proxy
  git config --global --unset https.proxy
}

