return {
  "lukas-reineke/indent-blankline.nvim",
  lazy = true,
  event = "BufReadPost",
  opts = {
    enabled = true,
    bufname_exclude = { "README.md" },
    buftype_exclude = { "terminal", "nofile" },
    filetype_exclude = {
      "alpha",
      "log",
      "gitcommit",
      "dapui_scopes",
      "dapui_stacks",
      "dapui_watches",
      "dapui_breakpoints",
      "dapui_hover",
      "dbui",
      "UltestSummary",
      "UltestOutput",
      "vimwiki",
      "markdown",
      "txt",
      "vista",
      "NvimTree",
      "git",
      "TelescopePrompt",
      "undotree",
      "org",
      "orgagenda",
      "help",
      "startify",
      "dashboard",
      "packer",
      "Outline",
      "Trouble",
      "lspinfo",
      "", -- for all buffers without a file type
    },
    char = "▏",
    -- char_list = { "", "┊", "┆", "¦", "|", "¦", "┆", "┊", "" },
    -- char_highlight_list = {
    --   "IndentBlanklineIndent1",
    -- },
    -- show_end_of_line = false,
    show_trailing_blankline_indent = false,
    show_first_indent_level = true,
    space_char_blankline = " ",
    use_treesitter = false,
    show_foldtext = false,
    show_current_context = true,
    show_current_context_start = false,
    context_patterns = {
      "class",
      "return",
      "function",
      "method",
      "import",
      "^if",
      "^do",
      "^switch",
      "^while",
      "^for",
      "^object",
      "^table",
      "jsx_element",
      "block",
      "arguments",
      "if_statement",
      "else_clause",
      "try_statement",
      "catch_clause",
      "import_statement",
      "operation_type",
      "list_literal",
    },
  },
  init = function()
    vim.g.indent_blankline_char = "▏"
    vim.api.nvim_create_autocmd("CursorMoved", { command = "IndentBlanklineRefresh" })
  end,
  cmd = {
    "IndentBlanklineRefresh",
    "IndentBlanklineEnable",
    "IndentBlanklineDisable",
    "IndentBlanklineToggle",
  },
  keys = {
    { "[oi", "<cmd>IndentBlanklineEnable<CR>", desc = "Indent Line" },
    { "]oi", "<cmd>IndentBlanklineDisable<CR>", desc = "Indent Line" },
    { "yoi", "<cmd>IndentBlanklineToggle<CR>", desc = "Indent Line" },
  },
}
